### Get all applications
GET http://localhost:8083/api/applications

### Get single application

GET http://localhost:8083/api/applications/599d305d-4884-4e45-9625-d47e3917950b

### Get single application, not existing

GET http://localhost:8083/api/applications/1ab86e65-0170-412f-bfd0-2242158c17dd

### Get disk's applications

GET http://localhost:8083/api/disks/053073ac-6189-411b-b4f8-513742a2b3b1/applications

### Get disk's applications, empty

GET http://localhost:8083/api/disks/012f799c-8754-4c5d-a997-a9cf83b5ff41/applications

### Get disk's applications, not existing

GET http://localhost:8083/api/disks/02ac4c57-4427-4fdb-9b54-01419d769032/applications

### Create new application

PUT http://localhost:8083/api/applications/cb6d73f4-22bc-4490-8c22-17ac76fc58b3
Content-Type: application/json

{
  "name": "Minecraft",
  "size": 12,
  "disk": "012f799c-8754-4c5d-a997-a9cf83b5ff41"
}

### Create new application, existing

PUT http://localhost:8083/api/applications/599d305d-4884-4e45-9625-d47e3917950b
Content-Type: application/json

{
  "name": "Counter-Strike 2",
  "size": 52,
  "disk": "012f799c-8754-4c5d-a997-a9cf83b5ff41"
}
### Update application

PATCH http://localhost:8083/api/applications/599d305d-4884-4e45-9625-d47e3917950b
Content-Type: application/json

{
  "name": "Paint",
  "size": 10
}

### Delete application

DELETE http://localhost:8083/api/applications/e12e3cdc-2b9e-4e83-9a7c-4aac3a7a1191

### Delete disk

DELETE http://localhost:8083/api/disks/053073ac-6189-411b-b4f8-513742a2b3b1

### Add disk
PUT http://localhost:8083/api/disks/0dcbbbe6-6585-4d70-adcf-30fd47edee5c
Content-Type: application/json

{
  "name": "Music",
  "size": 128
}

### Add app to the disk

PUT http://localhost:8083/api/applications/af81caff-7c6b-464a-90a6-c9631591bc02
Content-Type: application/json

{
  "name": "Musicly",
  "size": 52,
  "disk": "0dcbbbe6-6585-4d70-adcf-30fd47edee5c"
}

### Update disk

PATCH http://localhost:8083/api/disks/053073ac-6189-411b-b4f8-513742a2b3b1
Content-Type: application/json

{
  "name": "Other",
  "size": 256
}